@startuml

participant "ESP32" as device
box "WebSocket"
participant "/wsc" as wsc
participant "/ws" as ws
wsc <-[dashed]-> ws : event bus
end box
participant "Browser" as user

device -> wsc : connect
wsc -> ws: register device

device -> wsc : telemetry

user -> ws : connect

user -> ws : list devices
ws -> user : device list

user -> ws : assume device
ws -> wsc : assume device
wsc -> device : assume device
wsc -> device : camera on
wsc -> ws : device assumed
ws -> user : device assumed

device -> wsc : telemetry
wsc -> ws : telemetry
ws -> user : telemetry

device -> wsc : camera
wsc -> ws : camera
ws -> user : camera

user -> ws : control device
ws -> wsc : control device
wsc -> device : control device

user -> ws : leave device, disconnect
ws -> wsc : leave device
wsc -> device : leave device
wsc -> device : camera off
wsc -> ws : device left

device -> wsc : disconnect
wsc -> ws : unregister device

@enduml